name: Build ROM for Houji
on:
  workflow_dispatch:
    inputs:
      URL:
        description: "移植包下载地址"
        required: true
        default: 'https://bkt-sgp-miui-ota-update-alisgp.oss-ap-southeast-1.aliyuncs.com/OS1.0.10.0.UNPCNXM/miui_PERIDOT_OS1.0.10.0.UNPCNXM_91bb9533db_14.0.zip'
      CUSTOM_VERSION:
        description: "待打包版本号"
      VENDOR_URL:
        description: "底包下载地址"
        required: true
        default: 'https://bkt-sgp-miui-ota-update-alisgp.oss-ap-southeast-1.aliyuncs.com/OS1.0.24.4.22.DEV/miui_HOUJI_OS1.0.24.4.22.DEV_d623167a4b_14.0.zip'
      IMAGE_TYPE:
          description: "IMAGE 格式"
          required: true
          default: 'erofs'
          type: choice
          options:
          - erofs
          - ext4
      EXT_RW:
          description: 'EXT4 可读写'
          required: true
          type: boolean
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 最大化构建环境
        uses: easimon/maximize-build-space@master
        with:
          swap-size-mb: 8192
          root-reserve-mb: 4096
          temp-reserve-mb: 4096
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
      - name: 检出仓库文件
        uses: actions/checkout@main
        with:
          repository: MicroWater/Build_Houji_Rom
          token: ${{ secrets.PAT }}
      - name: 构建 ROM
        run: |
          sudo bash "$GITHUB_WORKSPACE"/make.sh ${{ github.event.inputs.URL }} ${{ github.event.inputs.VENDOR_URL }} $GITHUB_ENV $GITHUB_WORKSPACE
      - name: 处理 ROM
        run: |
          mkdir -p "$GITHUB_WORKSPACE"/GithubRelease
          cd "$GITHUB_WORKSPACE"/GithubRelease
          sudo split -b 1536M -d "$GITHUB_WORKSPACE"/zip/${{ env.rom_name }} ${{ env.rom_name }}
          cd "$GITHUB_WORKSPACE"
          touch file.log
          echo -e "底包版本: ${{ env.vendor_os_version }}\n底包安全补丁版本: ${{ env.vendor_security_patch }}\n底包基线版本: ${{ env.vendor_base_line}}\n\n移植包版本: ${{ env.port_os_version }}\n移植包安全补丁版本: ${{ env.port_security_patch }}\n移植包基线版本: ${{ env.port_base_line }}" > file.log
      - name: 上传到 Github Release
        uses: ncipollo/release-action@main
        with:
          artifacts: ${{ github.workspace }}/GithubRelease/*
          name: ${{ env.port_os_version }}
          tag: ${{ env.port_os_version }}
          bodyFile: "${{ github.workspace }}/file.log"
          allowUpdates: true
          artifactErrorsFailBuild: true
      - name: 上传到 OneDrive
        run: |
          sudo -v ; curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone/
          echo ${{ secrets.confbase64 }} > base64.txt
          base64 --decode base64.txt > ~/.config/rclone/rclone.conf
          rclone copy -P "$GITHUB_WORKSPACE"/zip/${{ env.rom_name }} e5:/刷机包/HOUJI
